apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.repoPrefix }}${{ values.name }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
